#!/usr/bin/env python
import csv
import json
import os
import re
import sys
from pathlib import Path

directory = Path(os.path.dirname(os.path.dirname(os.path.realpath(__file__))))


def main(path):
    codes = {
        # https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#User-assigned_code_elements
        'XK': 'Kosovo',
    }

    with open(path) as f:
        rpc = json.load(f)[0]['rpc'][0]
        offset = int(rpc[0])

        for entry in rpc[3][1]:
            d = entry['d']
            codes[d[str(offset + 9)]] = re.sub(r' \(the\)|\*', '', d[str(offset + 13)])

            assert d[str(offset + 9)] == d[str(offset + 15)]

    with open(directory / 'codelists' / 'country.csv', 'w') as f:
        writer = csv.DictWriter(f, fieldnames=['Code', 'Title'], lineterminator='\n')
        writer.writeheader()

        for code in sorted(codes):
            writer.writerow({
                'Code': code,
                'Title': codes[code],
            })


if __name__ == '__main__':
    main(sys.argv[1])
